version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - logger.level=trace  # Increase logging verbosity to TRACE
    ports:
      - "9200:9200"
    networks:
      - esnet
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  esnet:
