# Use version 3.8 of the Docker Compose file format
version: '3.8'

services:
  # Elasticsearch service configuration
  elasticsearch:
    # Use the official Elasticsearch image
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      # Set the discovery type to single-node for standalone operation
      - discovery.type=single-node
    ports:
      # Map port 9200 on the host to port 9200 on the Elasticsearch container
      - "9200:9200"
    networks:
      # Connect Elasticsearch to the 'esnet' network
      - esnet

  # Apache Beam service configuration
  beam:
    # Build the Beam image from the Dockerfile in the parent directory
    build:
      context: ../
      dockerfile: docker/Dockerfile
      cache_from:
        - beam:latest  # Use the latest Beam image as cache

    # Specify that Beam service depends on Elasticsearch service
    depends_on:
      - elasticsearch
    networks:
      # Connect Beam to the 'esnet' network
      - esnet

# Define the 'esnet' network
networks:
  esnet:
