version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  beam:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      cache_from:
        - beam:latest
    depends_on:
      - elasticsearch
    networks:
      - esnet
volumes:
  esdata:
    driver: local
networks:
  esnet:
    driver: bridge
